### ISSUE TITLE
Minimum Python version

### ISSUE THREAD

**Issue by hoijui** [sassanh/python-strtobool#2]
Does this really require python 3.9?
Or did you set it to that because before, there were other options for the same functionality?
It would be useful for this to work over a wider range of python versions, or else one has to write conditional code for different versions, using internal python functionality or this one.. which kind of defeats the purpose of using this library.

**Comment by sassanh** [comment]
Which Python version are you working with? Is 3.8 enough?

**Comment by sassanh** [comment]
The thing is while it is not depending on newer versions of Python, latest versions of some dev dependencies like poethepoet and pytest-cov do rely on newer Python versions.

**Comment by hoijui** [comment]
ahh... and it is not possible to define different minimum python versions for the two (dev and "normal")?

To be honest, I don't remember which version I needed... :/
I now just c&p'ed the implementation of `str_to_bool` from Python 3.8.2 into my project.
I am a dev, but do not usually use python.

**Comment by sassanh** [comment]
Thanks for the feedback, I dropped the required version to 3.0.0

**Comment by hoijui** [comment]
wohoo, cool; thank you! :-)
I replaced the c&p'ed code with the lib; works well! :-)
